### ISSUE TITLE
Improve the UI design of the website using React.js

### ISSUE THREAD

**Issue by NerdyWithZainab** [NerdyWithZainab/Music-Concert-Website#1]
**Tasks**
- [ ] Converting this website into a React.js web application.
- [ ] Improve the UI of the Web App
- [ ] Clicking a button using Javascript
- [ ] Improve the appearance of the social media links
- [ ] Deploy the Web App
- [ ] Add a dark mode option
- [ ] Adding Security
